let frase =
  "toda ciência seria supérflua se houvesse coincidência imediata entre a aparência e a essência das coisas";

let quantidade = frase.split("a").length - 1;

console.log(quantidade);

/*O que o código faz?
O script conta quantas vezes a letra "a" aparece na citação de Karl Marx. Ele faz isso transformando a frase em um array (lista),
usando a própria letra "a" como o separador, e depois medindo o tamanho desse array.

Principais Funções e Elementos
.split("a"): Esta função "quebra" a string em todas as posições onde encontra a letra "a". Por exemplo,
se tivéssemos "casa".split("a"), o resultado seria um array de três partes: ["c", "s", ""].

.length: Retorna o número de elementos no array gerado pelo split.

- 1: Esta é a lógica matemática crucial. Se você divide algo em 2 partes, você fez 1 corte. Se divide em 3 partes, 
fez 2 cortes. Portanto, o número de letras "a" é sempre o número de pedaços menos um.

console.log(): Exibe o total final no console.

Aplicações Práticas
Análise de Texto: Contar a frequência de palavras ou letras para análise linguística simples.

Validação de Senhas: Verificar se um usuário incluiu caracteres obrigatórios (como "@" ou "." em e-mails).

Processamento de CSV: Contar quantas vírgulas existem em uma linha para validar a estrutura de um arquivo de dados.

English: Code Explanation

The script counts how many times the letter "a" appears in the Karl Marx quote. It achieves this by turning the sentence into an array (list), 
using the letter "a" itself as the separator, and then measuring the size of that array.

Key Functions and Elements
.split("a"): This function "breaks" the string at every position where it finds the letter "a". For instance, if we had "banana".split("a"), the result would be ["b", "n", "n", ""].

.length: Returns the number of elements in the array generated by the split method.

- 1: This is the crucial mathematical logic. If you split something into 2 parts, you made 1 cut. If you split it into 3 parts,
you made 2 cuts. Therefore, the number of "a"s is always the number of pieces minus one.

console.log(): Prints the final count to the console.

Practical Applications
Text Analysis: Counting the frequency of words or letters for basic linguistic analysis.

Password Validation: Checking if a user included required characters (like "@" or "." in email addresses).

CSV Processing: Counting how many commas exist in a line to validate the structure of a data file.

Nota Técnica / Technical Note:
Este código é case-sensitive. Ele contará apenas o "a" minúsculo. Para contar tanto "a" quanto "A", 
o código precisaria de uma Expressão Regular ou de uma conversão prévia para minúsculas: frase.toLowerCase().split("a"). */
